trigger:
  branches:
    include:
      - dev


pool:
  name: 'development'

variables:
  dockerRegistryServiceConnection: 'Docker-connection'
  frontendImageName: 'suharsh2000/frontend'
  backendImageName: 'suharsh2000/backend'
  tag: 'dev-$(Build.BuildId)'

stages:
  - stage: BuildAndDeploy
    jobs:
      - deployment: DevDeploy
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  displayName: Build & Push Frontend
                  inputs:
                    command: buildAndPush
                    dockerfile: docker/frontend/Dockerfile
                    repository: $(frontendImageName)
                    containerRegistry: $(dockerRegistryServiceConnection)
                    tags: |
                      $(tag)

                - task: Docker@2
                  displayName: Build & Push Backend
                  inputs:
                    command: buildAndPush
                    dockerfile: docker/backend/Dockerfile
                    repository: $(backendImageName)
                    containerRegistry: $(dockerRegistryServiceConnection)
                    tags: |
                      $(tag)

                - script: echo "✅ Deployment to DEV completed!"
