trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: adelaidefringe-variables

stages:
- stage: DeployToDev
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
  - deployment: Deploy
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'your-azure-subscription'
              appName: 'adelaidefringe-dev'
              containers: |
                $(frontendImageName):latest
                $(backendImageName):latest

- stage: DeployToTest
  condition: eq(variables['Build.SourceBranchName'], 'test')
  jobs:
  - deployment: Deploy
    environment: testing
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'your-azure-subscription'
              appName: 'adelaidefringe-test'
              containers: |
                $(frontendImageName):latest
                $(backendImageName):latest

- stage: DeployToProd
  condition: eq(variables['Build.SourceBranchName'], 'main')
  jobs:
  - deployment: Deploy
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'your-azure-subscription'
              appName: 'adelaidefringe-prod'
              containers: |
                $(frontendImageName):latest
                $(backendImageName):latest
