trigger:
  branches:
    include:
      - main
      

pool:
  name: 'development'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U


variables:
  dockerRegistryServiceConnection: 'Docker-connection'
  frontendImageName: 'suharsh2000/frontend'
  backendImageName: 'suharsh2000/backend'
  tag: '$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:

          #  Docker access debug step
          - script: |
              whoami
              docker version
              docker info
            displayName: 'Verify Docker Access from Agent'

          - task: Docker@2
            displayName: 'Build & Push Frontend'
            inputs:
              command: buildAndPush
              repository: $(frontendImageName)
              dockerfile: docker/frontend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: 'Build & Push Backend'
            inputs:
              command: buildAndPush
              repository: $(backendImageName)
              dockerfile: docker/backend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
