trigger:
  branches:
    include:
      - main
      - dev
      - test

pool:
  vmImage: 'ubuntu-latest'  

variables:
  dockerRegistryServiceConnection: 'Docker-connection'
  frontendImageName: 'adelaidefringe/frontend'
  backendImageName: 'adelaidefringe/backend'
  tag: '$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: 'Build & Push Frontend'
            inputs:
              command: buildAndPush
              repository: $(frontendImageName)
              dockerfile: docker/frontend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: 'Build & Push Backend'
            inputs:
              command: buildAndPush
              repository: $(backendImageName)
              dockerfile: docker/backend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
