stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
          - script: docker --version
            displayName: 'Check Docker Version'

          - task: Docker@2
            displayName: 'Build & Push Frontend'
            inputs:
              command: buildAndPush
              repository: $(frontendImageName)
              dockerfile: docker/frontend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
